In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix  


In [2]:
trainset = pd.read_csv("/home/dragneel/Documents/DataScience/Dataset-ori-before-C5.0/Malware-TrainingSet.csv")
testset = pd.read_csv("/home/dragneel/Documents/DataScience/Dataset-ori-before-C5.0/Malware-TestingSet.csv")

In [3]:
x_train = trainset.drop(["Family"], axis=1)
x_train.head(10)

2Grammed_APICalls_#0  2Grammed_APICalls_#1  2Grammed_APICalls_#2  \
0                     0                    42                     0   
1                     2                     0                     0   
2                     0                    40                     0   
3                     0                    43                     0   
4                     2                    43                     0   
5                     1                    49                     0   
6                     0                     2                     0   
7                     0                     0                     0   
8                     0                     0                     0   
9                     0                     0                     0   

   2Grammed_APICalls_#3  2Grammed_APICalls_#4  2Grammed_APICalls_#5  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   
5                     0                     0                     0   
6                     0                     0                     0   
7                     0                     0                     0   
8                     0                     0                     0   
9                     0                     0                     0   

   2Grammed_APICalls_#6  2Grammed_APICalls_#7  2Grammed_APICalls_#8  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   
5                     0                     0                     0   
6                     0                     0                     0   
7                     0                     0                     0   
8                     0                     0                     0   
9                     0                     0                     0   

   2Grammed_APICalls_#9  ...  act_data_pkt_fwd  min_seg_size_forward  \
0                     0  ...                48                  1156   
1                     0  ...                52                  1003   
2                     0  ...                62                  1377   
3                     0  ...                68                  1530   
4                     0  ...                59                  1373   
5                     0  ...                55                  1140   
6                     0  ...                89                  1572   
7                     0  ...                92                  1462   
8                     0  ...                89                  1327   
9                     0  ...                45                  1101   

   Active_Mean  Active_Std  Active_Max  Active_Min  Idle_Mean  Idle_Std  \
0     15852488      281828    16119128    15653804  170240589  19488345   
1      5625453      438112     6270008     5271904  166045107   8283170   
2     17206799      607301    17801215    16789493  246965228  22019770   
3     20024831      540635    20464751    19626959  218034819  31463640   
4     17770612      334061    18098131    17539051  200495551  20186565   
5     17014120      183305    17241587    16902074  217349829  15946075   
6     10378685     1139999    11536613     9542941  283416561  18705949   
7      6704967      984013     7620780     5975211  330046674  21655290   
8      7801122      839608     8610396     7066799  320075418  14981874   
9      6383579      368684     6746241     6140808  152739489  19663481   

    Idle_Max   Idle_Min  
0  186397186

In [4]:
y_train = trainset["Family"]
y_train.head(10)


0        koler
1        koler
2        koler
3        koler
4        koler
5        koler
6       svpeng
7       svpeng
8       svpeng
9    lockerpin
Name: Family, dtype: object

In [5]:
x_test = testset.drop(["Family"], axis=1)
x_test.head(10)

2Grammed_APICalls_#0  2Grammed_APICalls_#1  2Grammed_APICalls_#2  \
0                     2                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   
5                     0                     1                     1   
6                     0                     1                     0   
7                     0                     1                     0   
8                     0                     0                     0   
9                     0                     0                     0   

   2Grammed_APICalls_#3  2Grammed_APICalls_#4  2Grammed_APICalls_#5  \
0                     0                     0                     2   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   
5                     4                     1                     1   
6                     8                     1                     1   
7                     2                     1                     1   
8                     0                     0                     1   
9                     0                     0                     0   

   2Grammed_APICalls_#6  2Grammed_APICalls_#7  2Grammed_APICalls_#8  \
0                     2                     0                     4   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   
5                     1                     2                     3   
6                     1                     4                     7   
7                     1                     1                     1   
8                     0                     0                     0   
9                     0                     0                     0   

   2Grammed_APICalls_#9  ...  act_data_pkt_fwd  min_seg_size_forward  \
0                     3  ...               106                  3006   
1                     0  ...                83                  1495   
2                     0  ...               102                  1718   
3                     0  ...               107                  2167   
4                     0  ...                69                  1196   
5                     1  ...                35                   719   
6                     2  ...                65                   928   
7                     0  ...                51                   889   
8                     0  ...                58                790425   
9                     0  ...                66                  1026   

   Active_Mean  Active_Std  Active_Max  Active_Min  Idle_Mean  Idle_Std  \
0      9749451     1033082    10855054     8772935  219314233  12445580   
1      8455869     1370902     9746442     7502681  275933150  17745168   
2      7720706     1886119     9681185     6401865  265548961  23474759   
3     14451858     2416412    16785206    12714143  380691833  31552614   
4      7757972     1121967     9090378     6512722  158328982  11256570   
5      3896629      252390     4126118     3708588  111767341  14337954   
6      7325382     1197903     8603577     5907164  162009225  13467553   
7      5695727      499108     6144178     5326065  176249135  17279682   
8      6201877      675056     6841359     5592287  234172380  11560015   
9      7463004     1025991     8532468     6614443  212686552  13535066   

    Idle_Max   Idle_Min  
0  231621111

In [6]:
y_test = testset["Family"]
y_test.head(10)

0         koler
1        svpeng
2        svpeng
3        svpeng
4     lockerpin
5         jisut
6         jisut
7         jisut
8    simplocker
9    simplocker
Name: Family, dtype: object

In [7]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
lb.fit(y_train)
 
y_train = lb.transform(y_train)
y_test = lb.transform(y_test)

In [8]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(x_train)

x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test)

In [9]:
knn = KNeighborsClassifier( n_neighbors=3, p=2, metric='euclidean')
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [10]:
from time import time

start = time()
y_pred = knn.predict(x_test)
end = time()
result = end-start
print(y_pred)
print()
print('Time = %f seconds' % result)

[26  4 36  3 11 11 19 19 23  3  1  8  8  2  2 28 28 28 29 24 21 11  5 17
  9  4  9  0  1  4 24  3  2  5  1  3  2 10 10  2 10  2  5  5  5  0  0  0
  0  0  1 24 17  4 24 17 14 14 12 12  4 12 26 26 26  1  9  1  3 23  6 15
  6 15 15 15 15 15 15 15  6  6 18 38 15  1  2 21 18 33 33 33 10 17  2  7
  3 33 33 33  8  8  3  2 17  3  0 24 14  1 15 15 15 15 15 33]

Time = 0.066968 seconds


In [11]:
from sklearn.metrics import accuracy_score
print ('Accuracy Score :')
accuracy_score(y_test,y_pred)

Accuracy Score :


0.3879310344827586

In [12]:
from sklearn.metrics import classification_report, confusion_matrix  
print('==================Confusion Metrix :=======================')
print(confusion_matrix(y_test, y_pred)) 
print()
print('==================classification_report :==================')
print(classification_report(y_test, y_pred))
print('=====================Accuracy Score========================')
print(accuracy_score(y_test,y_pred))
print('==========================Timer============================')
print('Time = %f seconds' % result)

==================Confusion Metrix :=======================
[[6 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]

==================classification_report :==================
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       0.12      0.50      0.20         2
           2       0.00      0.00      0.00         2
           3       0.12      0.25      0.17         4
           4       0.20      1.00      0.33         1
           5       0.60      0.75      0.67         4
           6       0.00      0.00      0.00         5
           7       0.00      0.00      0.00         1
           8       1.00      1.00      1.00         4
           9       0.67      0.67      0.67         3
          10       0.75      0.75      0.75         4
          11       0.00      0.00      0.00         2
          12       1.00      0.75      0.86         4
  

/home/dragneel/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [13]:
from sklearn.metrics import plot_confusion_matrix
class_names = dataset.Family
#plt.figure(figsize=(20, 20))
fig, ax = plt.subplots(figsize=(20, 20))
plot_confusion_matrix(knn, x_test, y_test, display_labels=class_names, cmap=plt.cm.inferno , ax=ax )
plt.title('Confusion matrix')
plt.show()

ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics' (/home/dragneel/anaconda3/lib/python3.7/site-packages/sklearn/metrics/__init__.py)

In [78]:
cnf_matrix = confusion_matrix(y_test, y_pred)

FP = cnf_matrix.sum(axis=0) - np.diag(cnf_matrix) 
FN = cnf_matrix.sum(axis=1) - np.diag(cnf_matrix)
TP = np.diag(cnf_matrix)
TN = cnf_matrix.sum() - (FP + FN + TP)

FP = FP.astype(int)
FN = FN.astype(int)
TP = TP.astype(int)
TN = TN.astype(int)

In [79]:
print("============================================")
print(TP)
print("============================================")
print(TN)
print("============================================")
print(FP)
print("============================================")
print(FN)

[6 1 0 1 1 3 0 0 4 2 3 0 3 0 3 2 0 1 0 2 0 0 0 1 0 0 3 0 3 1 0 0 0 4 0 0 0
 0 1]
[109 107 105 105 111 110 107 114 112 112 111 111 112 112 113 101 112 110
 110 113 113 113 115 110 109 112 111 113 113 114 115 114 114 109 113 112
 114 114 112]
[ 1  7  9  7  4  2  4  1  0  1  1  3  0  0  0 12  0  4  2  0  0  2  0  1
  5  0  1  0  0  0  0  0  0  3  0  0  1  0  0]
[0 1 2 3 0 1 5 1 0 1 1 2 1 4 0 1 4 1 4 1 3 1 1 4 2 4 1 3 0 1 1 2 2 0 3 4 1
 2 3]


In [80]:
TPP = np.sum(TP)
TNN = np.sum(TN)
FPP = np.sum(FP)
FNN = np.sum(FN)

print(TPP)
print(TNN)
print(FPP)
print(FNN)

45
4337
71
71


In [81]:
Recall = TPP/(TPP+FNN)
print(Recall)
Precision = TPP/(TPP+FPP)
print(Precision)
Akurasi = (TPP+TNN)/(TPP+FPP+FNN+TNN)
print(Akurasi)

0.3879310344827586
0.3879310344827586
0.9686118479221928


In [82]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_test, y_pred)

array([[[109,   1],
        [  0,   6]],

       [[107,   7],
        [  1,   1]],

       [[105,   9],
        [  2,   0]],

       [[105,   7],
        [  3,   1]],

       [[111,   4],
        [  0,   1]],

       [[110,   2],
        [  1,   3]],

       [[107,   4],
        [  5,   0]],

       [[114,   1],
        [  1,   0]],

       [[112,   0],
        [  0,   4]],

       [[112,   1],
        [  1,   2]],

       [[111,   1],
        [  1,   3]],

       [[111,   3],
        [  2,   0]],

       [[112,   0],
        [  1,   3]],

       [[112,   0],
        [  4,   0]],

       [[113,   0],
        [  0,   3]],

       [[101,  12],
        [  1,   2]],

       [[112,   0],
        [  4,   0]],

       [[110,   4],
        [  1,   1]],

       [[110,   2],
        [  4,   0]],

       [[113,   0],
        [  1,   2]],

       [[113,   0],
        [  3,   0]],

       [[113,   2],
        [  1,   0]],

       [[115,   0],
        [  1,   0]],

       [[110,   1],
        [  4, 

In [14]:
dataset = pd.read_csv ("/home/dragneel/Documents/DataScience/Dataset-ori-before-C5.0/Daataset-Full-before-C5.0.csv")
dataset

2Grammed_APICalls_#0  2Grammed_APICalls_#1  2Grammed_APICalls_#2  \
0                       0                    42                     0   
1                       2                     0                     0   
2                       0                    40                     0   
3                       0                    43                     0   
4                       2                    43                     0   
..                    ...                   ...                   ...   
300                     0                     2                     0   
301                     0                     0                     0   
302                     0                     0                     0   
303                     0                     0                     0   
304                     0                     0                     0   

     2Grammed_APICalls_#3  2Grammed_APICalls_#4  2Grammed_APICalls_#5  \
0                       0                     0                     0   
1                       0                     0                     0   
2                       0                     0                     0   
3                       0                     0                     0   
4                       0                     0                     0   
..                    ...                   ...                   ...   
300                     0                     0                     0   
301                     0                     0                     0   
302                     0                     0                     0   
303                     0                     0                     0   
304                     0                     0                     0   

     2Grammed_APICalls_#6  2Grammed_APICalls_#7  2Grammed_APICalls_#8  \
0                       0                     0                     0   
1                       0                     0                     0   
2                       0                     0                     0   
3                       0                     0                     0   
4                       0                     0                     0   
..                    ...                   ...                   ...   
300                     0                     0                     0   
301                     0                     0                     0   
302                     0                     0                     0   
303                     0                     0                     0   
304                     0                     0                     0   

     2Grammed_APICalls_#9  ...  min_seg_size_forward  Active_Mean  Active_Std  \
0                       0  ...                  1156     15852488      281828   
1                       0  ...                  1003      5625453      438112   
2                       0  ...                  1377     17206799      607301   
3                       0  ...                  1530     20024831      540635   
4                       0  ...                  1373     17770612      334061   
..                    ...  ...                   ...          ...         ...   
300                     0  ...                   193      4246991      187950   
301                     0  ...                   239      1545328      170631   
302                     0  ...                   170       399598      134479   
303                     0  ...                   175       450493      167882   
304                     0  ...                  1253     17653289      916279   

     Active_Max  Active_Min  Idle_Mean  Idle_Std   Idle_Max   Idle_Min  \
0      16119128    15653804  170240589  19488345  186397186  155416258   
1       6270008     5271904  166045107   8283170  173387076  159763065   
2      17801215    16789493  246965228  22019770  263938727  230197339   
3      20464751    19626959  218034819  31463640  242915705  194688432   
4      18098131    17539051  20

In [15]:
x = dataset.drop(["Family"],axis=1)
x.head(10)

2Grammed_APICalls_#0  2Grammed_APICalls_#1  2Grammed_APICalls_#2  \
0                     0                    42                     0   
1                     2                     0                     0   
2                     0                    40                     0   
3                     0                    43                     0   
4                     2                    43                     0   
5                     1                    49                     0   
6                     0                     2                     0   
7                     0                     0                     0   
8                     0                     0                     0   
9                     0                     0                     0   

   2Grammed_APICalls_#3  2Grammed_APICalls_#4  2Grammed_APICalls_#5  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   
5                     0                     0                     0   
6                     0                     0                     0   
7                     0                     0                     0   
8                     0                     0                     0   
9                     0                     0                     0   

   2Grammed_APICalls_#6  2Grammed_APICalls_#7  2Grammed_APICalls_#8  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   
5                     0                     0                     0   
6                     0                     0                     0   
7                     0                     0                     0   
8                     0                     0                     0   
9                     0                     0                     0   

   2Grammed_APICalls_#9  ...  act_data_pkt_fwd  min_seg_size_forward  \
0                     0  ...                48                  1156   
1                     0  ...                52                  1003   
2                     0  ...                62                  1377   
3                     0  ...                68                  1530   
4                     0  ...                59                  1373   
5                     0  ...                55                  1140   
6                     0  ...                89                  1572   
7                     0  ...                92                  1462   
8                     0  ...                89                  1327   
9                     0  ...                45                  1101   

   Active_Mean  Active_Std  Active_Max  Active_Min  Idle_Mean  Idle_Std  \
0     15852488      281828    16119128    15653804  170240589  19488345   
1      5625453      438112     6270008     5271904  166045107   8283170   
2     17206799      607301    17801215    16789493  246965228  22019770   
3     20024831      540635    20464751    19626959  218034819  31463640   
4     17770612      334061    18098131    17539051  200495551  20186565   
5     17014120      183305    17241587    16902074  217349829  15946075   
6     10378685     1139999    11536613     9542941  283416561  18705949   
7      6704967      984013     7620780     5975211  330046674  21655290   
8      7801122      839608     8610396     7066799  320075418  14981874   
9      6383579      368684     6746241     6140808  152739489  19663481   

    Idle_Max   Idle_Min  
0  186397186

In [16]:
y = dataset["Family"]
y.head(10)

0        koler
1        koler
2        koler
3        koler
4        koler
5        koler
6       svpeng
7       svpeng
8       svpeng
9    lockerpin
Name: Family, dtype: object

In [17]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()
lb.fit(y)
 
y= lb.transform(y)

In [18]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(x)

x = scaler.transform(x)  


In [19]:
from sklearn.model_selection import cross_val_score
import numpy as np#create a new KNN model

knn_cv = KNeighborsClassifier(n_neighbors=3, p=2, metric = 'euclidean')#train model with cv of 5 
cv_scores = cross_val_score(knn_cv, x,y, cv=5)#print each cv score (accuracy) and average them

print(cv_scores)
print("===========================================================")
print("cv_scores mean:{}".format(np.mean(cv_scores)))

/home/dragneel/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


[0.41891892 0.42424242 0.46774194 0.44444444 0.40816327]
cv_scores mean:0.4327021976791562


In [20]:
from numpy import mean
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

# create model
model = (KNeighborsClassifier(n_neighbors=3, p=2, metric = 'euclidean'))
# evaluate model
scores = cross_val_score(model, x, y, scoring='accuracy', cv=10)
# report performance
print(scores)
print('Accuracy: %.3f' % (mean(scores)))

/home/dragneel/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


[0.4        0.425      0.35       0.47222222 0.42857143 0.55882353
 0.5        0.63636364 0.44444444 0.42857143]
Accuracy: 0.464


In [90]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
y = np.array([number[0] for number in lb.fit_transform(y)])

recall = cross_val_score(model, x, y, cv=10, scoring='recall')
print('Recall', np.mean(recall), recall)
print("====================================================================")
precision = cross_val_score(model, x, y, cv=10, scoring='precision')
print('Precision', np.mean(precision), precision)
print("====================================================================")

Recall 0.55 [0.5 1.  0.  0.5 0.  1.  1.  0.  1.  0.5]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Precision 0.7 [1. 1. 0. 1. 0. 1. 1. 0. 1. 1.]
